"""
PDF Report generation service using ReportLab.
Generates professional medical-style PDF reports.
"""
import logging
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚠️ IMPORTANT DISCLAIMER: This report is generated by an AI-assisted tool "
    "and is NOT a medical diagnosis. The predicted conditions are suggestions only, "
    "based on symptom analysis. Please consult a qualified healthcare professional "
    "for proper diagnosis and treatment."
)


class PDFService:
    """Generates downloadable PDF reports from session analysis data."""

    def generate_report(self, report_data: dict, output_path: str = None) -> str:
        """
        Generate a PDF medical report.

        Args:
            report_data: Dict with keys:
                - patient_name: str (optional)
                - session_id: str
                - transcription: str
                - translated_text: str
                - language: str
                - symptoms: list[str]
                - severity: str | None
                - duration: str | None
                - diseases: list[dict] (disease, confidence_pct, rank)
                - generated_at: str (ISO timestamp)
            output_path: Where to save PDF. Uses temp file if not given.

        Returns:
            Path to the generated PDF file.
        """
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table,
            TableStyle, HRFlowable, KeepTogether,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

        if output_path is None:
            tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
            output_path = tmp.name
            tmp.close()

        BLUE = colors.HexColor("#0066CC")
        LIGHT_BLUE = colors.HexColor("#E8F0FE")
        GREEN = colors.HexColor("#00A878")
        RED = colors.HexColor("#DC3545")
        DARK_GRAY = colors.HexColor("#2D3748")
        LIGHT_GRAY = colors.HexColor("#F8FAFC")

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "Title",
            parent=styles["Title"],
            fontSize=22,
            textColor=BLUE,
            spaceAfter=6,
            alignment=TA_CENTER,
        )
        subtitle_style = ParagraphStyle(
            "Subtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=DARK_GRAY,
            alignment=TA_CENTER,
            spaceAfter=12,
        )
        section_header_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=BLUE,
            spaceBefore=14,
            spaceAfter=6,
            borderPad=4,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=10,
            textColor=DARK_GRAY,
            spaceAfter=4,
            leading=15,
            alignment=TA_JUSTIFY,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=9,
            textColor=RED,
            spaceAfter=4,
            leading=14,
            alignment=TA_JUSTIFY,
        )
        label_style = ParagraphStyle(
            "Label",
            parent=styles["Normal"],
            fontSize=10,
            textColor=DARK_GRAY,
            leading=15,
        )

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        story = []
        now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
        gen_at = report_data.get("generated_at", now)

        # ─── Header ────────────────────────────────────────────────────────
        story.append(Paragraph("🏥 AI Clinical Assistant", title_style))
        story.append(Paragraph("Medical Conversation Intelligence System", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=BLUE))
        story.append(Spacer(1, 0.3 * cm))

        # Report metadata table
        session_id = report_data.get("session_id", "—")
        patient_name = report_data.get("patient_name") or "Anonymous Patient"
        language = report_data.get("language_name", "English")

        meta_data = [
            ["Report Generated", gen_at],
            ["Session ID", session_id[:16] + "..."],
            ["Patient", patient_name],
            ["Audio Language", language],
        ]
        meta_table = Table(meta_data, colWidths=[5 * cm, 12 * cm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), LIGHT_BLUE),
            ("TEXTCOLOR", (0, 0), (0, -1), BLUE),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY, colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.4 * cm))

        # ─── Disclaimer ────────────────────────────────────────────────────
        disclaimer_box_data = [[Paragraph(DISCLAIMER, disclaimer_style)]]
        disclaimer_box = Table(disclaimer_box_data, colWidths=[17 * cm])
        disclaimer_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFF5F5")),
            ("BOX", (0, 0), (-1, -1), 1, RED),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(disclaimer_box)
        story.append(Spacer(1, 0.4 * cm))

        # ─── Transcription / Conversation ──────────────────────────────────
        story.append(Paragraph("1. Conversation Transcription", section_header_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 0.2 * cm))

        transcription = report_data.get("translated_text") or report_data.get("transcription", "")
        if transcription:
            story.append(Paragraph(transcription[:2000], body_style))
        else:
            story.append(Paragraph("No transcription available.", body_style))

        was_translated = report_data.get("was_translated", False)
        if was_translated:
            orig = report_data.get("original_text", "")
            story.append(Spacer(1, 0.15 * cm))
            story.append(Paragraph(
                f"<b>Original ({language}):</b> {orig[:500]}",
                ParagraphStyle("SmallItalic", parent=body_style, fontSize=8, textColor=colors.gray)
            ))

        # ─── Extracted Symptoms ─────────────────────────────────────────────
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("2. Extracted Symptoms", section_header_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 0.2 * cm))

        symptoms = report_data.get("symptoms", [])
        severity = report_data.get("severity")
        duration = report_data.get("duration")

        if symptoms:
            # Symptom chips in table
            symptom_rows = []
            row = []
            for i, sym in enumerate(symptoms):
                row.append(Paragraph(f"• {sym.title()}", label_style))
                if (i + 1) % 3 == 0:
                    symptom_rows.append(row)
                    row = []
            if row:
                while len(row) < 3:
                    row.append(Paragraph("", label_style))
                symptom_rows.append(row)

            sym_table = Table(symptom_rows, colWidths=[5.5 * cm, 5.5 * cm, 6 * cm])
            sym_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BLUE),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.white),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_BLUE, colors.HexColor("#EEF4FF")]),
            ]))
            story.append(sym_table)
        else:
            story.append(Paragraph("No specific symptoms extracted.", body_style))

        # Severity + Duration
        story.append(Spacer(1, 0.2 * cm))
        meta2 = []
        if severity:
            meta2.append(["Severity", severity.title()])
        if duration:
            meta2.append(["Duration", duration])

        if meta2:
            m_table = Table(meta2, colWidths=[4 * cm, 13 * cm])
            m_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), LIGHT_BLUE),
                ("TEXTCOLOR", (0, 0), (0, -1), BLUE),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(m_table)

        # ─── Disease Predictions ────────────────────────────────────────────
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("3. AI-Suggested Probable Conditions", section_header_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            "<i>⚠️ These are AI-generated suggestions based on symptom similarity. "
            "They are NOT diagnoses. Confidence scores reflect semantic similarity only.</i>",
            ParagraphStyle("SmallNote", parent=body_style, fontSize=8, textColor=colors.HexColor("#E53E3E"))
        ))
        story.append(Spacer(1, 0.2 * cm))

        diseases = report_data.get("diseases", [])
        if diseases:
            disease_rows = [
                [
                    Paragraph("<b>Rank</b>", label_style),
                    Paragraph("<b>Suggested Condition</b>", label_style),
                    Paragraph("<b>Similarity Score</b>", label_style),
                ]
            ]
            for d in diseases:
                pct = d.get("confidence_pct", 0)
                disease_rows.append([
                    Paragraph(f"#{d.get('rank', '?')}", label_style),
                    Paragraph(d.get("disease", "—")[:100], body_style),
                    Paragraph(f"{pct}%", label_style),
                ])

            d_table = Table(disease_rows, colWidths=[1.5 * cm, 13 * cm, 2.5 * cm])
            d_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BLUE]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(d_table)
        else:
            story.append(Paragraph("No disease predictions available.", body_style))

        # ─── Recommendations ────────────────────────────────────────────────
        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph("4. General Recommendations", section_header_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 0.15 * cm))

        recs = [
            "1. Consult a qualified medical professional for proper diagnosis and treatment.",
            "2. Do not self-medicate based on AI predictions.",
            "3. Bring this report to your healthcare provider for reference.",
            "4. If symptoms are severe or worsening, seek immediate medical attention.",
            "5. Keep a symptom diary noting frequency, severity, and any triggers.",
        ]
        for rec in recs:
            story.append(Paragraph(rec, body_style))

        # ─── Footer ─────────────────────────────────────────────────────────
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(width="100%", thickness=1, color=BLUE))
        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            "AI Clinical Assistant | Powered by Whisper, NLLB, and Sentence-BERT | "
            "This is NOT a substitute for professional medical advice.",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.gray, alignment=TA_CENTER)
        ))

        doc.build(story)
        logger.info(f"✅ PDF report generated: {output_path}")
        return output_path
